www-birds/config/routes.rb
Rails.application.routes.draw do

  root 'birds#index'

  get 'span' => 'span#index'

  get 'weight' => 'weight#index'

  get 'lost' => 'lost#index'

  

end

www-birds/app/models/appearance.rb
class Appearance < ActiveRecord::Base
end

www-birds/app/models/span.rb
class Span < ActiveRecord::Base
end

www-birds/app/models/weight.rb
class Weight < ActiveRecord::Base
end

www-birds/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :gen_prime

  def is_prime ( p )
    return true  if p == 2
    return false if p <= 1 || p.even?
    (3 .. Math.sqrt(p)).step(2) do |i|
      return false  if p % i == 0
    end
    true
  end

  def is_mersenne_prime ( p )
    return true  if p == 2
    m_p = ( 1 << p ) - 1
    s = 4
    (p-2).times { s = (s ** 2 - 2) % m_p }
    s == 0
  end

  def gen_prime
    precision = 150   # maximum requested number of decimal places of 2 ** MP-1 #
    long_bits_width = precision / Math.log(2) * Math.log(10)
    upb_prime = (long_bits_width - 1).to_i / 2    # no unsigned #
    upb_count = 45      # find 45 mprimes if int was given enough bits #

    count = 0
    (2..upb_prime).each { |p|
      if is_prime(p) && is_mersenne_prime(p)
        count += 1
      end
      break if count >= upb_count
    }
  end

end

www-birds/app/controllers/birds_controller.rb
class BirdsController < ApplicationController

	def index
	end
	
end

www-birds/app/controllers/lost_controller.rb
class LostController < ApplicationController

  def index
    @lost = Appearance.where("last_seen < ?", 1.week.ago)
                .order(:last_seen, :bird_tag)
                .paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.html
      format.json {
        render json: {
                   :current_page => @lost.current_page,
                   :per_page => @lost.per_page,
                   :total_entries => @lost.total_entries,
                   :entries => @lost
               }
      }
    end
  end

end

www-birds/app/controllers/span_controller.rb
class SpanController < ApplicationController

  def index
    if params[:date]
      date_param = Date.strptime(params[:date], '%d-%m-%Y')
      @info = Span.where(date: date_param)
                  .paginate(page: params[:page], per_page: 10)
      respond_to do |format|
        format.html
        format.json {
          render json: {
                     :current_page => @info.current_page,
                     :per_page => @info.per_page,
                     :total_entries => @info.total_entries,
                     :entries => @info
                 }
        }
      end
    else
      respond_to do |format|
        format.html
        format.json {
          render json: {
                     :current_page => 0,
                     :per_page => 0,
                     :total_entries => 0,
                     :entries => []
                 }
        }
      end
    end
  end

end

www-birds/app/controllers/weight_controller.rb
class WeightController < ApplicationController

	def index
		@towers = Weight.select(:tower_id).order(:tower_id).distinct
		if params[:date]
			date_param = Date.strptime(params[:date], '%d-%m-%Y')
			@stats = Weight.where(:date => date_param, :tower_id =>  params[:tower_id])
			respond_to do |format|
				format.html
				format.json { render json: @stats }
			end
		else
			respond_to do |format|
				format.html
				format.json { render json: [] }
			end
		end
	end

end

www-birds/app/helpers/appearance_helper.rb
module AppearanceHelper
end

www-birds/app/helpers/application_helper.rb
module ApplicationHelper
end

www-birds/app/helpers/span_helper.rb
module SpanHelper
end

www-birds/app/helpers/weight_helper.rb
module WeightHelper
end

www-birds/app/views/birds/index.html.erb
<div class="jumbotron">
  <h1 class="text-center">Welcome to the birds observation center!</h1>
  <ul class="link-list">
  	<li>
      <a href="<%= span_path %>">Find the tower that observed the bird with biggest wingspan in raining
        conditions</a>
  	</li>
  	<li>
  		<a href="<%= weight_path %>">Get the total added estimated weight of all the birds seen by a tower</a>
  	</li>
  	<li>
  		<a href="<%= lost_path %>">All tagged birds that have not been observed for more than one week</a>
  	</li>
  </ul>
</div>

www-birds/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="full">
<head>
  <title>Birds Observation Center</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Bird Observation', '/', class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="header-navbar">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if params[:controller] == 'birds' %>">
          <%= link_to 'Home', controller: 'birds', action: 'index' %>
        </li>
        <li class="<%= 'active' if params[:controller] == 'span' %>">
          <%= link_to 'Wing span', controller: 'span', action: 'index' %>
        </li>
        <li class="<%= 'active' if params[:controller] == 'weight' %>">
          <%= link_to 'Estimated weight', controller: 'weight', action: 'index' %>
        </li>
        <li class="<%= 'active' if params[:controller] == 'lost' %>">
          <%= link_to 'Lost birds', controller: 'lost', action: 'index' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
		<%= yield %>
</div>

<div class="footer">
   <div class="container">
      <p class="text-muted text-center">Developed by KKN Team. 2014 &copy;</p>
   </div>
</div>
</body>
</html>

www-birds/app/views/lost/index.html.erb
<div class="row">
  <div class="jumbotron">
    <h3>There are <%= pluralize(@lost.total_entries, 'bird')%>
      that have not been observed for more than one week.</h3>
    <table class="table table-striped table-hover table-bordered">
      <thead>
        <tr>
          <th>Bird tag</th>
          <th>Last observation</th>
        </tr>
      </thead>
      <tbody>
        <% @lost.each do |info| %>
          <tr>
            <td><%= info.bird_tag %></td>
            <td><%= info.last_seen %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="text-center">
      <%= will_paginate @lost, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

www-birds/app/views/span/index.html.erb
<div class="row jumbotron">
    <h3>Find the tower that observed the bird with biggest wingspan in raining
      conditions.</h3>

    <%= form_tag span_path, method: :get, role: 'form', class: 'form-inline' do %>
      <div class="form-group">
        <%= label_tag(:date, "Select date:", class: 'control-label') %>
        <%= text_field_tag(:date,
                           (params[:date] or Time.now.strftime '%d-%m-%Y'),
                           class: 'form-control datepicker') %>
      </div>
      <div class="form-group">
        <%= submit_tag('Search', class: 'btn btn-default') %>
      </div>
    <% end %>

    <% if @info %>
      <div class="search-result">
        <h4>Result</h4>
        <table class="table table-striped table-hover table-bordered">
          <tr>
            <th>Tower</th>
            <th>Wingpan</th>
          </tr>
          <% @info.each do |row| %>
            <tr>
              <td><%= row.tower_id %></td>
              <td><%= row.maxspan %></td>
            </tr>
          <% end %>
        </table>
        <div class="text-center">
          <%= will_paginate @info, renderer: BootstrapPagination::Rails %>
        </div>
      </div>
    <% end %>
</div>

www-birds/app/views/weight/index.html.erb
<div class="row">
	<div class="jumbotron">
		<h3>Get the total added estimated weight of all the birds seen by a tower.</h3>
		<br/>
		<%= form_tag weight_path, method: :get, :class => 'form-inline' do %>
          <div class="form-group">
            <%= label_tag(:date, 'Select date:', class: 'control-label') %>
            <%= text_field_tag(:date,
                               (params[:date] or Time.now.strftime '%d-%m-%Y'),
                               class: 'form-control datepicker') %>
          </div>
          <div class="form-group">
            <%= label_tag(:tower_id, 'Tower id:', class: 'control-label') %>
            <%= select_tag(
                    :tower_id,
                    options_from_collection_for_select(@towers,
                                                      :tower_id,
                                                      :tower_id),
                    class: 'form-control'
                )
            %>
          </div>
          <div class="form-group">
            <%= submit_tag('Search', class: 'btn btn-default') %>
          </div>
		<% end %>

    <% if @stats %>
      <div class="search-result">
        <h4>Result</h4>
        <h2>
          <% @stats.each do |info| %>
            <td><%= info.weight %></td>
          <% end %>
        </h2>
      </div>
    <% end %>
	</div>
</div>